docs: add an rfc to unify the gateway interfaces
axelarnetwork/cgp-spec pull request #5
Opened 2023-06-09 16:32 UTC by cgorenflo

2023-06-09 16:55 UTC, cjcobb23 requested changes
Left a couple of comments, main thing missing though is some function on the gateway to actually execute the message at the final destination.

2023-06-09 16:55 UTC, cjcobb23 commented on rfc-unified-gateways .md
> +}
We need a call for when the payload is actually executed on the final destination chain. It could just be `ExecuteMsgs`. It is either called by the dApp itself, and it simply marks the message as executed (like we do on EVM chains). Or it could actually execute the contract call itself.

2023-06-09 16:55 UTC, cjcobb23 commented on rfc-unified-gateways .md
> +A user calls `CallContract` with the appropriate payload on Ethereum. The gateway prepares the routing message and registers the payload with a payload verifier. It calls `VerifyMsgs`, which returns
I like this direct routing, as it's probably cheaper as well as lower latency. However, for token transfers, it's probably better to always go through Axelar, otherwise it can be complicated to unwrap a wrapped token (since you would need to traverse the same path you used to wrap it in order to unwrap it). For example, if a user bridged AXL from Axelar to Ethereum and then to Arbitrum, and then wanted to bridge the token back to Axelar, they would need to bridge from Arbitrum to Ethereum and then to Axelar, instead of just directly back to Axelar.

2023-06-09 16:55 UTC, cjcobb23 commented on rfc-unified-gateways .md
> +In many cases it is probably enough to call functions just with `Message` ID. For the sake of simplicity I chose to use `Message` everywhere in this proposal.
Using just the ID prior to verification is generally unsafe, because there could be two unverified packets with the same ID, and the protocol needs to be able to distinguish one from the other. We can use a hash of the full routing packet though, since two different packets will always hash to a different value, even if they are trying to use the same ID. We could also explore actually making the ID just the hash of the contents, though then verifiers like the voting verifier won't be able to actually locate the appropriate transaction on the source chain.

2023-06-12 13:19 UTC, sergeynog commented on rfc-unified-gateways .md
> +In many cases it is probably enough to call functions just with `Message` ID. For the sake of simplicity I chose to use `Message` everywhere in this proposal.
hash of the routing packet might not be unique either. the only only we get a unique ID in EVM-based chains is after the TX is finalized.

2023-06-12 13:22 UTC, sergeynog commented on rfc-unified-gateways .md
> +This proposal aims to unify the interface for all gateways. Furthermore, it allows different routing mechanisms depending on the route (e.g. native routing for L2s/IBC, routing through axelar otherwi
storing all messages in a storage is expensive, that's why we emit events only at the EVM chains. 
so for internal routing / receive -> we can store. for outgoing messages, we should emit only.

2023-06-12 17:12 UTC, haiyizxx commented on rfc-unified-gateways .md
> +A user calls `CallContract` with the appropriate payload on Avalanche. The gateway prepares the routing message and registers the payload with a payload verifier. It calls `VerifyMsgs`, which returns
> It calls `VerifyMsgs`, which returns true because of the previously mentioned verifier
what is pervasively mentioned verifier and what does return true means?

2023-06-12 17:15 UTC, cgorenflo commented on rfc-unified-gateways .md
> +A user calls `CallContract` with the appropriate payload on Avalanche. The gateway prepares the routing message and registers the payload with a payload verifier. It calls `VerifyMsgs`, which returns
the payload verifier, which just returns true, i.e. "verified", if the gateway asks it for a msgs for which the payload is known

2023-06-12 17:23 UTC, haiyizxx commented on rfc-unified-gateways .md
> +A user calls `CallContract` with the appropriate payload on Avalanche. The gateway prepares the routing message and registers the payload with a payload verifier. It calls `VerifyMsgs`, which returns
kk, if the call contract happens on Avalanche (the source), why it needs the payload verifier on itself?

2023-06-12 17:26 UTC, haiyizxx commented on rfc-unified-gateways .md
> +A user calls `CallContract` with the appropriate payload on Avalanche. The gateway prepares the routing message and registers the payload with a payload verifier. It calls `VerifyMsgs`, which returns
Oh, I got it. The payload verifier is also responsible for verify remote post a message to the gateway. So source call payload verifier will always return true?

2023-06-12 17:44 UTC, sammy1991106 commented on rfc-unified-gateways .md
> +A user calls `CallContract` with the appropriate payload on Avalanche. The gateway prepares the routing message and registers the payload with a payload verifier. It calls `VerifyMsgs`, which returns
So you are considering letting the destination chain's gateway, i.e. the one on moonbeam, store the msg after `RouteMsgs` is called but before the multisig proof arrives?

2023-06-12 17:44 UTC, sammy1991106 commented on rfc-unified-gateways .md
> +Potentially, we could remove the need for verification check and optimistically route. Execution on the destination chain would then wait until the verification has caught up with the routing (or not
Don't think simple overrule is enough for doing things optimistically. You'd have to punish and economically disincentivize bad behaviours to make it work.

2023-06-12 17:44 UTC, sammy1991106 commented on rfc-unified-gateways .md
> +  CallContract(string: destination chain, string: destination address, []byte payload)
At this point, why even keeping this function at all? It's just `RouteMsgs`, which only routes verified messages, no?

2023-06-14 16:33 UTC, cjcobb23 commented on rfc-unified-gateways .md
> +  CallContract(string: destination chain, string: destination address, []byte payload)
We need this on external chains I think, but I'm not sure what this should do on axelarnet

2023-06-15 15:09 UTC, cjcobb23 commented on rfc-unified-gateways .md
> +	RouteMsgs([]Message: msgs)
Does `RouteMsgs` prevent routing the same message twice?

2023-06-19 04:17 UTC, cgorenflo commented on rfc-unified-gateways .md
> +A user calls `CallContract` with the appropriate payload on Avalanche. The gateway prepares the routing message and registers the payload with a payload verifier. It calls `VerifyMsgs`, which returns
correct

2023-06-19 04:21 UTC, cgorenflo commented on rfc-unified-gateways .md
> +  CallContract(string: destination chain, string: destination address, []byte payload)
`CallContract` is the actual endpoint for contracts to call, which translates a payload that needs to be called into a routable message. So it triggers routing and can emit events with the payload. We need a starting point like this, otherwise we don't have the payload. On axelarnet it's only necessary if we allow contracts on the network that want to call out to another chain

2023-06-19 04:21 UTC, cgorenflo commented on rfc-unified-gateways .md
> +	RouteMsgs([]Message: msgs)
no, we should only prevent double spending on the destination

2023-06-19 04:23 UTC, cgorenflo commented on rfc-unified-gateways .md
> +Potentially, we could remove the need for verification check and optimistically route. Execution on the destination chain would then wait until the verification has caught up with the routing (or not
yeah, in the end there is not much incentive to implement optimistic routing when we already have gmp express

2023-06-19 04:26 UTC, cgorenflo commented on rfc-unified-gateways .md
> +A user calls `CallContract` with the appropriate payload on Avalanche. The gateway prepares the routing message and registers the payload with a payload verifier. It calls `VerifyMsgs`, which returns
register the payload means when the corresponding message asks if it was verified, this verifier will return true if it has seen the payload before (to make sure we can relay it to the destination)
I took out all unnecessary storage now to be less prescriptive. If we want to go with this the proof would need to be provided before the gateway would store the msg

2023-06-20 16:02 UTC, cjcobb23 commented on cgp-cosmwasm-v1.md
> +A user calls `CallContract` with the appropriate payload on Avalanche. The gateway prepares the routing message and sends the payload to a payload verifier. Then it calls its own `Route` function. `R
> Axelarons relayers listen for the routing event, pick up the message and broadcast it to `gateway.Route(msg)` on axelarnet. Routing on axelarnet is blocked until the voting verifiers are done with their confirmation, after which `gateway.Route(msg)` calls `router.Route(msg)` on the registered router contract.

I'm a little unclear on the flow here. The relayer calls `Route`, but the message is not yet verified, so it doesn't get routed. The voting verifier later verifes the message. Once it's verified, does the relayer call `Route` again?

2023-06-21 14:18 UTC, cjcobb23 approved these changes

2023-06-21 15:43 UTC, merged